# Generated by Django 2.1.3 on 2019-03-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compile', '0002_auto_20190301_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='code2',
            field=models.FileField(default='', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
