# Generated by Django 2.1.5 on 2019-04-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compile', '0003_coder_code2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coder',
            old_name='code1',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='coder',
            name='code2',
        ),
        migrations.AddField(
            model_name='coder',
            name='score',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
