# Generated by Django 2.1.5 on 2019-04-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compile', '0004_auto_20190406_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='qno',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
